version: '3'
services:
  tensorflow:
    build: ./Dockerfile.App
    container_name: tensorflow
    ports:
      - "6080:80"
    volumes:
      - .:/home/project
    networks:
      static-network:
        ipv4_address: 172.20.0.2
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
          #docker-compose v3+ do not use ip_range
          ip_range: 192.168.0.1/24
